version: 2
jobs:
  build:
    docker:
      - image: google/dart:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dart pub
      - run:
          name: Run tests
          command: dart test/newServer_test.dart
