version: 2
jobs:
  build:
    docker:
      - image: google/dart
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pub get
      - run:
          name: Build server
          command: dart compile exe newServer.dart -o newServer
      - run:
          name: Start server
          command: ./newServer
